
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-03
owner: ucsb-cs156-f25
repo_name: team02-f25-03
pull_requests: [{"author":{"id":"MDQ6VXNlcjg3MjU4Mjc1","is_bot":false,"login":"adamw3455","name":""},"headRefName":"Adam-MenuItemReview-Index-Page","number":96,"title":"Implement MenuItemReview Index Page/Stories/Tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/96"},{"author":{"id":"MDQ6VXNlcjU4NzU3Nzgz","is_bot":false,"login":"TOXICXUHUAN","name":""},"headRefName":"Dylan-UCSBDiningCommonsMenuItem-placeholder","number":95,"title":"Dylan ucsb dining commons menu item placeholder","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/95"},{"author":{"id":"MDQ6VXNlcjg3MjU4Mjc1","is_bot":false,"login":"adamw3455","name":""},"headRefName":"Adam-MenuItemReview-Edit-Page","number":94,"title":"Finish MenuItemReview Edit Page/Stories/Tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/94"},{"author":{"id":"MDQ6VXNlcjg3MjU4Mjc1","is_bot":false,"login":"adamw3455","name":""},"headRefName":"Adam-MenuItemReview-Create-Page","number":93,"title":"Finish MenuItemReview Create Page/stories/tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/93"},{"author":{"id":"U_kgDOCM7fCA","is_bot":false,"login":"ChenchangWang1018","name":""},"headRefName":"Chenchang-ArticlesEditPage","number":91,"title":"Chenchang articles edit page","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/91"},{"author":{"id":"U_kgDOClGZww","is_bot":false,"login":"JoshuaChu2004","name":""},"headRefName":"Joshua-UCSBOrganizationPlaceholders","number":89,"title":"Joshua ucsb organization placeholders","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/89"},{"author":{"id":"U_kgDOCM7fCA","is_bot":false,"login":"ChenchangWang1018","name":""},"headRefName":"Chenchang-ArticlesCreatePage","number":87,"title":"Chenchang articles create page","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/87"},{"author":{"id":"MDQ6VXNlcjgwNjMwMDQx","is_bot":false,"login":"terryZhouqr","name":"terry"},"headRefName":"TZ-HelpRequest-backend","number":85,"title":"Tz help request backend","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/85"},{"author":{"id":"U_kgDODf2SeQ","is_bot":false,"login":"tarang-netizen","name":""},"headRefName":"Tarang-Create-Fixtures","number":77,"title":"Added fixtures for recommendation request","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/77"}]
