
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-03
owner: ucsb-cs156-f25
repo_name: team02-f25-03
pull_requests: [{"author":{"id":"U_kgDODf2SeQ","is_bot":false,"login":"tarang-netizen","name":""},"headRefName":"Tarang-RecommendationRequest-endtoend","number":148,"title":"Added End to End tests for Recommendation Request","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/148"},{"author":{"id":"MDQ6VXNlcjgwNjMwMDQx","is_bot":false,"login":"terryZhouqr","name":"terry"},"headRefName":"TZ-E2E-db","number":147,"title":"Terry HelpRequest End2End Test","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/147"}]
