
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-03
owner: ucsb-cs156-f25
repo_name: team02-f25-03
pull_requests: [{"author":{"id":"U_kgDODf2SeQ","is_bot":false,"login":"tarang-netizen","name":""},"headRefName":"Tarang-RecommendationRequestForm","number":110,"title":"Tarang recommendation request form","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/110"},{"author":{"id":"U_kgDOClGZww","is_bot":false,"login":"JoshuaChu2004","name":""},"headRefName":"Joshua-UCSBOrganizationEdit","number":109,"title":"Joshua ucsb organization edit","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/109"},{"author":{"id":"MDQ6VXNlcjgwNjMwMDQx","is_bot":false,"login":"terryZhouqr","name":"terry"},"headRefName":"editpage","number":108,"title":"TZ-Editpage-db","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/108"},{"author":{"id":"MDQ6VXNlcjgwNjMwMDQx","is_bot":false,"login":"terryZhouqr","name":"terry"},"headRefName":"TZ-createpage-db","number":107,"title":"create page","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/107"},{"author":{"id":"MDQ6VXNlcjg3MjU4Mjc1","is_bot":false,"login":"adamw3455","name":""},"headRefName":"Readme-TODO-Removal","number":106,"title":"Clean up README by removing starter code overview","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/106"},{"author":{"id":"MDQ6VXNlcjU4NzU3Nzgz","is_bot":false,"login":"TOXICXUHUAN","name":""},"headRefName":"Dylan-UCSBDiningCommonsMenuItem-indexpage","number":105,"title":"Dylan ucsb dining commons menu item indexpage","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/105"},{"author":{"id":"MDQ6VXNlcjU4NzU3Nzgz","is_bot":false,"login":"TOXICXUHUAN","name":""},"headRefName":"Dylan-UCSBDiningCommonsMenuItem-editpage","number":104,"title":"Dylan ucsb dining commons menu item editpage","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/104"},{"author":{"id":"U_kgDOClGZww","is_bot":false,"login":"JoshuaChu2004","name":""},"headRefName":"Joshua-UCSBOrganizationIndex","number":101,"title":"Joshua ucsb organization index","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/101"},{"author":{"id":"U_kgDOClGZww","is_bot":false,"login":"JoshuaChu2004","name":""},"headRefName":"Joshua-UCSBOrganizationCreate","number":99,"title":"Joshua ucsb organization create","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/99"}]
