
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-03
owner: ucsb-cs156-f25
repo_name: team02-f25-03
pull_requests: [{"author":{"id":"MDQ6VXNlcjg3MjU4Mjc1","is_bot":false,"login":"adamw3455","name":""},"headRefName":"Adam-MenuItemReview-IntegrationTest","number":125,"title":"MenuItemReview integration test","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/125"},{"author":{"id":"MDQ6VXNlcjU4NzU3Nzgz","is_bot":false,"login":"TOXICXUHUAN","name":""},"headRefName":"Dylan-UCSBDiningCommonsMenuItem-endtoend","number":124,"title":"Dylan ucsb dining commons menu item endtoend","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/124"},{"author":{"id":"MDQ6VXNlcjg3MjU4Mjc1","is_bot":false,"login":"adamw3455","name":""},"headRefName":"Adam-RecommendationRequest-Edit-Page","number":123,"title":"RecommendationRequest Edit Page, RecommendationRequest Fixture edits","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/123"},{"author":{"id":"MDQ6VXNlcjU4NzU3Nzgz","is_bot":false,"login":"TOXICXUHUAN","name":""},"headRefName":"Dylan-UCSBDiningCommonsMenuItem-integrationtest","number":121,"title":"DC - add integration test","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/121"},{"author":{"id":"MDQ6VXNlcjgwNjMwMDQx","is_bot":false,"login":"terryZhouqr","name":"terry"},"headRefName":"TZ-editandindex-db","number":116,"title":"editpage and indexpage","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/116"}]
