
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-03
owner: ucsb-cs156-f25
repo_name: team02-f25-03
pull_requests: [{"author":{"id":"MDQ6VXNlcjgwNjMwMDQx","is_bot":false,"login":"terryZhouqr","name":"terry"},"headRefName":"TZ-HelpRequest-backend","number":85,"title":"Tz help request backend","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/85"},{"author":{"id":"U_kgDOClGZww","is_bot":false,"login":"JoshuaChu2004","name":""},"headRefName":"Joshua-UCSBOrganizationForm","number":84,"title":"Joshua ucsb organization form","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/84"},{"author":{"id":"MDQ6VXNlcjg3MjU4Mjc1","is_bot":false,"login":"adamw3455","name":""},"headRefName":"Adam-MenuItemReview-Placeholder-Pages","number":83,"title":"Implement MenuItemReview Placeholder Index/Create/Edit pages, add MenuItemReview to Nav Bar","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/83"},{"author":{"id":"U_kgDOCM7fCA","is_bot":false,"login":"ChenchangWang1018","name":""},"headRefName":"Chenchang-ArticlesPlaceholder","number":82,"title":"Chenchang articles placeholder","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/82"},{"author":{"id":"U_kgDOCM7fCA","is_bot":false,"login":"ChenchangWang1018","name":""},"headRefName":"Chenchang-ArticlesTable","number":80,"title":"Chenchang articles table","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/80"},{"author":{"id":"MDQ6VXNlcjg3MjU4Mjc1","is_bot":false,"login":"adamw3455","name":""},"headRefName":"Adam-MenuItemReview-Form-Component","number":79,"title":"Adam menu item review form component","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/79"},{"author":{"id":"U_kgDODf2SeQ","is_bot":false,"login":"tarang-netizen","name":""},"headRefName":"Tarang-Create-Fixtures","number":77,"title":"Added fixtures for recommendation request","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/77"}]
