
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-03
owner: ucsb-cs156-f25
repo_name: team02-f25-03
pull_requests: [{"author":{"id":"MDQ6VXNlcjg3MjU4Mjc1","is_bot":false,"login":"adamw3455","name":""},"headRefName":"Adam-MenuItemReview-Form-Component","number":79,"title":"Adam menu item review form component","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/79"},{"author":{"id":"U_kgDOCM7fCA","is_bot":false,"login":"ChenchangWang1018","name":""},"headRefName":"Chenchang-ArticlesForm","number":78,"title":"Add ArticlesForm + tests + stories","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/78"},{"author":{"id":"U_kgDODf2SeQ","is_bot":false,"login":"tarang-netizen","name":""},"headRefName":"Tarang-Create-Fixtures","number":77,"title":"Added fixtures for recommendation request","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/77"},{"author":{"id":"MDQ6VXNlcjgwNjMwMDQx","is_bot":false,"login":"terryZhouqr","name":"terry"},"headRefName":"TZ-HelpRequest-backend","number":75,"title":"Tz help request frontend ","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/75"},{"author":{"id":"U_kgDOClGZww","is_bot":false,"login":"JoshuaChu2004","name":""},"headRefName":"Joshua-UCSBOrganizationFixtures","number":74,"title":"Joshua Organization Fixtures","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/74"}]
