
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-03
owner: ucsb-cs156-f25
repo_name: team02-f25-03
pull_requests: [{"author":{"id":"MDQ6VXNlcjgwNjMwMDQx","is_bot":false,"login":"terryZhouqr","name":"terry"},"headRefName":"TZ-team03","number":146,"title":"integration test","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/146"},{"author":{"id":"U_kgDOCM7fCA","is_bot":false,"login":"ChenchangWang1018","name":""},"headRefName":"Chenchang-E2E","number":144,"title":"Chenchang E2E for Article","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/144"},{"author":{"id":"U_kgDOCM7fCA","is_bot":false,"login":"ChenchangWang1018","name":""},"headRefName":"Chenchang-team03","number":143,"title":"Add Integration Test for Article","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/143"},{"author":{"id":"U_kgDOClGZww","is_bot":false,"login":"JoshuaChu2004","name":""},"headRefName":"Joshua-UCSBOrganizationWebIT","number":137,"title":"Joshua UCSBOrganization End 2 End IT","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/137"},{"author":{"id":"U_kgDOClGZww","is_bot":false,"login":"JoshuaChu2004","name":""},"headRefName":"Joshua-UCSBOrganizationIT","number":136,"title":"Joshua Organization IT Test","url":"https://github.com/ucsb-cs156-f25/team02-f25-03/pull/136"}]
